version: '3.8'
services:
  db:
    image: gelegit/bamboocardtest_db
    container_name: bamboocard_db
    ports:
      - "1435:1433"
    networks:
      bamboocard-app:
        aliases:
          - bamboocardtest_database

  web:
    image: gelegit/bamboocardtest
    container_name: bamboocard_web
    networks:
      - bamboocard-app
    ports:
      - "8080:8080"

networks:
  bamboocard-app:
    driver: bridge