services:
    bamboocardtest_web:
        image: ${DOCKER_REGISTRY-}bamboocardtest
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: bamboocardtest
        environment:
            - ASPNETCORE_URLS=http://*:8080
        ports:
            - "8080:8080"        
        depends_on:
            - bamboocardtest_database
            
            
    bamboocardtest_database:
        image: "mcr.microsoft.com/mssql/server"
        container_name: bamboocard_db
        ports:
            - "1435:1433"
        environment:
            SA_PASSWORD: "BambooCard123456"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"

volumes:
  nopcommerce_data:            